name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v3

    - name: Install modules
      run: pnpm install

    - name: Run ESLint
      run: pnpm lint