name: CI
on: pull_request
jobs:
  ci:
    name: Run linter and formatter
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install modules
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format:check
